require 'active_record'
require 'yaml'
require 'logger'
require './db/seeds'

namespace :db do
  MIGRATIONS_DIR = 'db/migrate'
  DATASOURCE_CONFIG = 'config/database.yml'
  config = YAML.load_file(DATASOURCE_CONFIG)
  environment = ENV["ENVIRONMENT"] ? ENV["ENVIRONMENT"] : "development"
  ActiveRecord::Base.establish_connection(config["db"][environment])
  ActiveRecord::Base.logger = Logger.new(STDOUT)

  desc 'Migrate the database'
  task :migrate do
    ActiveRecord::Migrator.migrate(MIGRATIONS_DIR, ENV["VERSION"] ? ENV["VERSION"].to_i : nil)
  end

  desc 'Roll back the databse schema to the previous version'
  task :rollback do
    ActiveRecord::Migrator.rollback(MIGRATIONS_DIR, ENV["STEP"] ? ENV["STEP"].to_i : 1)
  end

  desc 'insert test data'
  task :seed do
    Turks::LoadSeed.truncate
    Turks::LoadSeed.load
  end
end

namespace :mixi do
  desc 'add topics'
  task :add_topic do
  end
end

